<?php

putenv('DISPLAY_ERRORS_DETAILS=' . false);

putenv('TREINO_JUNTO_MYSQL_HOST=');
putenv('TREINO_JUNTO_MYSQL_DBNAME=');
putenv('TREINO_JUNTO_MYSQL_USER=');
putenv('TREINO_JUNTO_MYSQL_PASSWORD=');
putenv('TREINO_JUNTO_MYSQL_PORT=3306');